[package]
name = "tinyproto"
version = "1.0.0"
edition = "2021"

# [build]
# profiler = true

[lib]
name = "tinyproto"
path = "src/lib.rs"

[[bin]]
name = "unittest"
path = "unittest/main.rs"

[dependencies]
